SalaryV2/Controllers/EmpPayWagQazvinsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Dynamic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SalaryV2.Models;

namespace SalaryV2.Controllers
{
    public class EmpPayWagQazvinsController : Controller
    {
        private Storedb db = new Storedb();
        private Models.Corporate.CorporateDB CorDB = new Models.Corporate.CorporateDB();
        private Models.Old.OldStoredb DB = new Models.Old.OldStoredb();
        private List<EmpVm> _Employees;

        [AllowAnonymous]
        public ActionResult Search()
        {
            Session["Login"] = null;
            Session["e1"] = null;
            ViewBag.Contid = new SelectList(db.ContractTypes, "Contid", "Title");
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [AllowAnonymous]
        public ActionResult Search(Search Smodel, int? Contid)
        {
            Models.Log log = new Models.Log();
            log.IpAddress = utility.IpAddress.GetUserIP();
            if (Contid == 1)
            {
                if (ModelState.IsValid)
                {
                    var id = db.RandomNumbers.Where(r => r.acnt == Smodel.b2 && r.NationCode == Smodel.e1).FirstOrDefault();
                    if (id != null)
                    {
                        if (id.SequrityCode != Smodel.SequrityCode)
                        {
                            ViewBag.Message = "  شناسه امنیتی اشتباه وارد شده است دوباره تلاش کنید  ";
                            ViewBag.Contid = new SelectList(db.ContractTypes, "Contid", "Title", Contid);
                            return View();
                        }
                        else
                        {
                            var list = CorDB.vwPersonnels.Where(s => s.IdentificationCode == "4322967868").FirstOrDefault();
                            try
                            {

                                var EmployeeList = CorDB.vwPersonnels.Where(e => e.IdentificationCode == Smodel.e1 & e.AccountNo == Smodel.b2).OrderByDescending(s => s.PersonnelId).FirstOrDefault();

                                if (null == EmployeeList)
                                {
                                    return View();
                                }
                                Session["Login"] = true;

                                Session["e1"] = EmployeeList.IdentificationCode;

                                log.Time = DateTime.Now.ToShortTimeString();
                                log.Date = utility.PertionDate.Today();
                                log.NationCode = Smodel.e1;
                                log.Acnt = Smodel.b2;
                                log.Type = "ورود";
                                log.FullName = EmployeeList.FirstName + " " + EmployeeList.LastName;
                                log.ConType =Convert.ToString( Contid);
                                db.Logs.Add(log);
                                db.SaveChanges();
                                Session["Login"] = EmployeeList.AccountNo;
                                return RedirectToAction("Print", "vwCalculations", new { id = EmployeeList.PartyRef, e1 = EmployeeList.IdentificationCode });
                            }
                            catch (Exception e)
                            {

                                throw;
                            }
                        }
                    }
                    ViewBag.Contid = new SelectList(db.ContractTypes, "Contid", "Title");
                    ViewBag.Message = "موردی یافت نشد ،اطلاعات وارد شده صحیح نمیباشد.";
                }
                ViewBag.Contid = new SelectList(db.ContractTypes, "Contid", "Title");
                return View();
            }
            else if (Contid == 2)
            {
                if (ModelState.IsValid)
                {
                    var id = db.RandomNumbers.Where(r => r.acnt == Smodel.b2 && r.NationCode == Smodel.e1).FirstOrDefault();
                    if (id != null)
                    {
                        if (id.SequrityCode != Smodel.SequrityCode)
                        {
                            ViewBag.Message = "  شناسه امنیتی اشتباه وارد شده است دوباره تلاش کنید  ";
                        }
                        else
                        {
                            try
                            {
                                var Date = utility.PertionDate.Today();
                                var year = int.Parse(Date.Substring(0, 4));
                                var EmployeeList = db.EmpPayWagQazvins.Where(e => e.NationCode == Smodel.e1 && e.Acnt==Smodel.b2).ToList();
                               
                                TempData["EmployeeList"] = EmployeeList;
                                var Employeeinf = EmployeeList.FirstOrDefault();
                                TempData["Employeeinf"] = Employeeinf;

                                if (EmployeeList.Count <= 0 || EmployeeList.Count == null)
                                {
                                    ViewBag.Contid = new SelectList(db.ContractTypes, "Contid", "Title", Contid);
                                    ViewBag.Message = "  شماره حساب یا کد ملی به درستی وارد نشده است   ";

                                    return View();
                                }
                                Session["Login"] = true;
                                Session["e1"] = EmployeeList.Select(em => em.NationCode);
                                ViewBag.EmployeeInfo = EmployeeList;
                                log.Time = DateTime.Now.ToShortTimeString();
                                log.Date = utility.PertionDate.Today();
                                log.NationCode = Smodel.e1;
                                log.FullName = Employeeinf.Name +" "+ Employeeinf.Fmly;
                                log.Acnt = Smodel.b2;
                                log.Type = "ورود";
                                log.ConType = Convert.ToString(Contid);
                                db.Logs.Add(log);
                                db.SaveChanges();
                                Session["Login"] =Employeeinf.Acnt;
                                var Activebank =Employeeinf.Acnt ;
                                return RedirectToAction("Print", new { id = Activebank, e1 = Employeeinf.NationCode });

                            }
                            catch (Exception e)
                            {

                                throw;
                            }
                        }
                    }
                    ViewBag.Contid = new SelectList(db.ContractTypes, "Contid", "Title");
                    ViewBag.Message = "موردی یافت نشد ،اطلاعات وارد شده صحیح نمیباشد.";
                }
            }
            ViewBag.Contid = new SelectList(db.ContractTypes, "Contid", "Title");

            return View();
        }
        // GET: EmpPayWagQazvins
        public ActionResult Index()
        {
            return View(db.EmpPayWagQazvins.ToList());
        }

        [AllowAnonymous]
        public ActionResult Print(int? YearId, int? MonthId, string id = "", string e1 = "")
        {
            
            dynamic model = new ExpandoObject();
            ViewBag.MessageMonthNull = null;
            ViewBag.IsNew = true;
            if (string.IsNullOrEmpty(id) || string.IsNullOrEmpty(e1))
            {
                return RedirectToAction("search");
            }
            var yearTo = db.Years.Where(y => y.YearId == YearId).FirstOrDefault();
            var MonthTo = db.Months.Where(y => y.MonthId == MonthId).FirstOrDefault();
            
            ViewBag.IsNew = true;
            var YearNow = utility.PertionDate.CurrentYear();
            var MonthNow = utility.PertionDate.CurrentMonth();
            var yearT = db.Years.Where(y => y.YearId == YearId).FirstOrDefault();
            var MonthT = db.Months.Where(y => y.MonthId == MonthId).FirstOrDefault();
            var yyy = db.Years.Where(y => y.YearTitle == YearNow).FirstOrDefault();
            var mmm = db.Months.Where(y => y.Caption == MonthNow).FirstOrDefault();
            var yy = yyy.YearId;
            var mm = mmm.MonthId;
            var mmStr = mm.ToString();
            var hh = db.Months.ToList();
            var EmployeeList = (List<EmpPayWagQazvin>)TempData["EmployeeList"];
            var MyModle = EmployeeList.Select(s => new EmpVm()
            {
                Acnt =  s.Acnt ,
                FullName = s.Name + " " + s.Fmly,
                Fthr = s.Fthr,
                DedCodTit = s.DedCodTit,
                DedVal = s.DedVal,
                PayCodTit = s.PayCodTit,
                PayVal = s.PayVal,
                ExtCodTit = s.ExtCodTit,
                ExtVal = s.ExtVal,
                NationCode = s.NationCode,
                InsId = s.InsId,
                Branch = db.Branch.Where(b => b.Branch1 == s.Branch).Select(b => b.BranchDsc).FirstOrDefault(),
                Year = s.Year,
                Mnt = s.Mnt,
                EmpId = s.EmpId
            }).ToList();
            var Employee = MyModle.Where(m => m.Acnt == id).OrderByDescending(d => d.Year).ThenByDescending(d => d.Mnt).FirstOrDefault();
            var lastM = Convert.ToString(Employee.Mnt);
            var lastY = Convert.ToString(Employee.Year);
            var LastYy = db.Years.Where(y => y.YearTitle == lastY).FirstOrDefault();
            var LastMm = db.Months.Where(y => y.Caption == lastM).FirstOrDefault();
            var Em = MyModle.Where(m => m.Acnt == id && m.NationCode == e1).OrderByDescending(d => d.Year).ThenByDescending(d => d.Mnt).AsQueryable();

            if (YearId.HasValue && YearId.Value != 0 && MonthId.HasValue && MonthId.Value != 0)
            {

SalaryV2/Views/EmpPayWagQazvins/Delete.cshtml
@model SalaryV2.Models.EmpPayWagQazvin

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>EmpPayWagQazvin</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Flag)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Flag)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PayCodId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PayCodId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PayCodTit)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PayCodTit)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PayVal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PayVal)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DedCodId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DedCodId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DedCodTit)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DedCodTit)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DedVal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DedVal)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ExtCodId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ExtCodId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ExtCodTit)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ExtCodTit)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ExtVal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ExtVal)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ExtValDsc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ExtValDsc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MazId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MazId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Maz)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Maz)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HokmVal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HokmVal)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BankAcntTyp)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BankAcntTyp)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Acnt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Acnt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Bank)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Bank)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BankCardNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BankCardNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SentByEmail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SentByEmail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Branch)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Branch)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AllBranch)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AllBranch)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.InsId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.InsId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fthr)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fthr)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NationCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NationCode)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

SalaryV2/Views/EmpPayWagQazvins/Details.cshtml
@model SalaryV2.Models.EmpPayWagQazvin

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>EmpPayWagQazvin</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Flag)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Flag)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PayCodId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PayCodId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PayCodTit)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PayCodTit)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PayVal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PayVal)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DedCodId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DedCodId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DedCodTit)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DedCodTit)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DedVal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DedVal)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ExtCodId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ExtCodId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ExtCodTit)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ExtCodTit)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ExtVal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ExtVal)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ExtValDsc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ExtValDsc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MazId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MazId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Maz)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Maz)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HokmVal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HokmVal)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BankAcntTyp)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BankAcntTyp)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Acnt)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Acnt)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Bank)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Bank)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BankCardNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BankCardNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SentByEmail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SentByEmail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Branch)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Branch)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AllBranch)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AllBranch)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.InsId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.InsId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fthr)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fthr)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NationCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NationCode)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

SalaryV2/Views/EmpPayWagQazvins/Search.cshtml
@model SalaryV2.Models.Search
@{
    ViewBag.Title = "..: فرم بازیابی اطلاعات:..";
}
<style>
    .row {
        margin-right: 0;
    }
</style>
<style>
    /*body {
        font-family: Tahoma;
        font-size: medium
    }*/

    span {
        color: #a813a0;
        font-size: small
    }
</style>
@using (Html.BeginForm("search", "EmpPayWagQazvins", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="row">
        <div class="col-sm-12">
            <div class="panel panel-info">
                <div class=" panel-heading">
                    <p class="text-lg-center">
                        ..:  به سامانه فیش حقوقی کارکنان شهرداری قزوین خوش آمدید:..
                    </p>
                </div>
                <div class="panel-body text-sm-right">
                    <div class="row">
            <div class="col-md-6 col-xs-offset-3 ">
                <a href="@Url.Action("GenerateCode", "RandomNum")" class="btn btn-info ">
                    ایجاد شناسه امنیتی
                    <i class="fa fa-user-plus fa-2x"></i>

                </a>
            </div>
        </div>
                    <div class="row">
                        <div class="col-md-12">
                            @if (TempData["message"] != null)
                            {
                                <div class="alert alert-danger" style="color:#a30e0e;font-family:Tahoma;font-size:medium;text-align:center">
                                    @TempData["message"]
                                </div>
                            }
                        </div>
                    </div>
                    <div class="row">
                        <div class="alert-danger">
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        </div>
                        @if (!string.IsNullOrEmpty(ViewBag.Message))
                        {
                            <p></p>
                            <p style="text-align:center;color:darkred">
                                <span class="fa fa-bell-o faa-wrench animated " style="color:#a70808"></span>
                               @ViewBag.Message
                            </p>
                        }
                    </div>
                    <div class="row">
                        <div class="col-sm-5">
                            <div>
                                <div>
                                    <span class="fa fa-star faa-wrench animated " style="color:#a70808"></span>

                                    @Html.DropDownList("Contid", null, "---انتخاب نوع قرار داد---", new { @class = "form-control input-lg" })
                                </div>
                            </div>
                            <div>
                                <span class="fa fa-star faa-wrench animated " style="color:#a70808"></span>
                                کد ملی
                                <div style="">
                                    <div class="input-group" style="margin-bottom: 10px">
                                        <span class="input-group-addon">
                                            <i class="fa fa-user-circle fa-2x ">
                                            </i>
                                        </span>
                                        @Html.TextBoxFor(model => model.e1, new { @class = "form-control input-lg", placeholder = " کد ملی  ", autocomplete = "off" })
                                    </div>
                                    <b>
                                        @Html.ValidationMessageFor(model => model.e1, "", new { @class = "text-danger" })
                                    </b>
                                </div>
                            </div>
                            <div>
                                <span class="fa fa-star faa-wrench animated " style="color:#a70808"></span>
                                شماره حساب
                                <div style="">
                                    <div class="input-group " style="margin-bottom: 10px" id="datePicker">
                                        <span class="input-group-addon">
                                            <i class="fa fa-user-circle fa-2x">
                                            </i>
                                        </span>
                                        @Html.TextBoxFor(model => model.b2, new { @class = "form-control input-lg", placeholder = "شماره حساب  ", autocomplete = "off" })
                                    </div>
                                    <b>
                                        @Html.ValidationMessageFor(model => model.b2, "", new { @class = "text-danger" })
                                    </b>
                                </div>
                            </div>
                            <div>
                                <span class="fa fa-star faa-wrench animated " style="color:#a70808"></span>
                                شناسه امنیتی
                                <div style="">
                                    <div class="input-group " style="margin-bottom: 10px" id="datePicker">
                                        <span class="input-group-addon">
                                            <i class="fa fa-user-circle fa-2x">
                                            </i>
                                        </span>
                                        @Html.PasswordFor(model => model.SequrityCode, new { @class = "form-control input-lg", placeholder = "شناسه امنیتی  ", autocomplete = "off" })
                                    </div>
                                    <b>
                                        @Html.ValidationMessageFor(model => model.SequrityCode, "", new { @class = "text-danger" })
                                    </b>
                                </div>
                            </div>
                            <div class="text-center btn-lg">
                                <button class="btn  btn-warning  fa-x" data-last="Finish ">
                                    نمایش فیش حقوقی
                                    <i class="fa fa-arrow-circle-left"></i>
                                </button>
                            </div>
                        </div>
                        <div class="col-sm-7 text-right">
                            <p class="text-body">
                                <span class="fa fa-bell faa-wrench animate" style="color:#a70808"></span>
                                همکار گرامی :
                            </p>
                            <p>
                                <span class="fa fa-check "></span>
                                لطفا از مرورگر فایرفاکس استفاده نمائید.
                            </p>
                            <p>
                                <span class="fa fa-check "></span>
                                اگر تا کنون شناسه امنیتی دریافت نکرده اید  گزینه ایجاد شناسه امنیتی را کلیک نمائید توجه داشته باشید که دریافت یک بار شناسه امنیتی کافی می باشد  .
                            </p>
                            <p>
                                <span class="fa fa-check "></span>
                                پیامک حاوی شناسه امنیتی جهت مشاهده فیش ارسال خواهد شد.
                            </p>
                            <p>
                                <span class="fa fa-check "></span>
                                درصورت  تمایل برای تغییر شناسه امنیتی  گزینه ایجاد شناسه را کلیلک نمائید .
                            </p>
                            <p>
                                <span class="fa fa-check "></span>
                                در صورت بروز خطا در هنگام ثبت نام با شماره <strong>33361230</strong> سازمان فناوری اطلاعات و ارتباطات شهرداری قزوین تماس  حاصل فرمائید.
                            </p>
                        </div>
                    </div>
                </div>
               
            </div>
        </div>

    </div>
}