SalaryV2/Controllers/RandomNumController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.Entity;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SalaryV2.Models;

namespace SalaryV2.Controllers
{
    [Authorize]
    public class RandomNumController : ControllerBase
    {
        private Storedb db = new Storedb();
        private Models.Corporate.CorporateDB CorDB = new Models.Corporate.CorporateDB();
        // GET: RandomNum
        public ActionResult Index()
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("login", "account");
            }
            var List = db.RandomNumbers.OrderByDescending(o => o.EditDate).ToList();
            return View(db.RandomNumbers.ToList());
        }
        // GET: RandomNum/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RandomNumber randomNumber = db.RandomNumbers.Find(id);
            if (randomNumber == null)
            {
                return HttpNotFound();
            }
            return View(randomNumber);
        }
        [AllowAnonymous]
        public ActionResult SendCode(int id)
        {

            var List = db.RandomNumbers.Where(r => r.RandId == id).OrderByDescending(o => o.RandId).FirstOrDefault();
            return PartialView("_SendCode", List);
        }
        [HttpGet]
        [AllowAnonymous]
        public ActionResult GenerateCode()
        {
            ViewBag.Contid = new SelectList(db.ContractTypes, "Contid", "Title");
            return View();
        }
        [AllowAnonymous]
        public string GenerateString()
        {
            Random rand = new Random();

            const string Alphabet =
           "0123456789";
            int size = 6;
            char[] chars = new char[size];
            for (int i = 0; i < size; i++)
            {
                chars[i] = Alphabet[rand.Next(Alphabet.Length)];
            }

            return new string(chars);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [AllowAnonymous]
        public ActionResult GenerateCode(GetCode GetCode)
        {
            if (ModelState.IsValid)
            {
                var Code = GenerateString();
                RandomNumber InsertCode = new RandomNumber();
                if (GetCode.Contid == 1)
                {
                    {
                        var per = CorDB.vwPersonnels.Where(p => p.AccountNo == GetCode.b2 && p.IdentificationCode == GetCode.e1).FirstOrDefault();
                        var empProfile = CorDB.vwParties.Where(p => p.PartyId == per.PartyRef).FirstOrDefault();

                        if (empProfile != null)
                        {
                            if (empProfile.Phone != null)
                            {
                                if (db.RandomNumbers.Where(r => r.NationCode == empProfile.IdentificationCode && r.acnt == per.AccountNo).Count() > 0)
                                {
                                    var InstanceRand = db.RandomNumbers.Where(r => r.NationCode == empProfile.IdentificationCode && r.acnt == per.AccountNo).FirstOrDefault();
                                    InstanceRand.SequrityCode = Code.ToString();
                                    InstanceRand.EditDate = utility.PertionDate.Today();
                                    InsertCode.EditTime = Convert.ToString(DateTime.Now.ToShortTimeString());
                                    InstanceRand.NationCode = empProfile.IdentificationCode;
                                    //InstanceRand.Father = empProfile.na;
                                    InstanceRand.Fname = empProfile.Name;
                                    InstanceRand.Mobile = empProfile.Phone;
                                    InstanceRand.acnt = per.AccountNo;
                                    InstanceRand.Lname = empProfile.LastName;
                                    InstanceRand.Type =Convert.ToString(GetCode.Contid);
                                    InstanceRand.SequrityCode = Code.ToString();
                                    db.Entry(InstanceRand).State = EntityState.Modified;
                                    db.SaveChanges();
                                    utility.SmSSender.SendSmSCode(empProfile.Phone, empProfile.FullName, Code.ToString());
                                    TempData["message"] = "همکار گرامی پیامک حاوی کد شناسه امنیتی برای شما ارسال خواهد شد.......";
                                    return RedirectToAction("search", "EmpPayWagQazvins");
                                }
                                else
                                {
                                    InsertCode.SequrityCode = Code.ToString();
                                    InsertCode.EditDate = utility.PertionDate.Today();
                                    InsertCode.EditTime = Convert.ToString(DateTime.Now.ToShortTimeString());
                                    InsertCode.NationCode = empProfile.IdentificationCode;
                                    InsertCode.Fname = empProfile.Name;
                                    InsertCode.Mobile = empProfile.Phone;
                                    InsertCode.acnt = per.AccountNo;
                                    InsertCode.Lname = empProfile.LastName;
                                    InsertCode.Type = Convert.ToString(GetCode.Contid);

                                    InsertCode.Time = Convert.ToString(DateTime.Now.ToShortTimeString());
                                    InsertCode.Date = utility.PertionDate.Today();
                                    
                                    db.RandomNumbers.Add(InsertCode);
                                    db.SaveChanges();
                                    utility.SmSSender.SendSmSCode(empProfile.Phone, empProfile.FullName, Code.ToString());
                                    TempData["message"] = "همکار گرامی پیامک حاوی کد شناسه امنیتی برای شما ارسال خواهد شد.......";
                                    return RedirectToAction("search", "EmpPayWagQazvins");
                                }

                            }
                            else
                            {
                                TempData["message"] = "  شماره تماس  شما جهت ارسال شناسه امنیتی در ثبت نشده است  .     ";
                                return RedirectToAction("search", "EmpPayWagQazvins");
                            }

                        }
                       
                    }
                }
                else if (GetCode.Contid == 2)
                {


                    var Suser = db.EmpPayWagQazvins.Where(d => d.NationCode == GetCode.e1 && d.Acnt == GetCode.b2).OrderByDescending(y => y.Year).ThenByDescending(y => y.Mnt).FirstOrDefault();

                    var TelMobil = Convert.ToString(Suser.TelMobil);
                    if (string.IsNullOrEmpty(TelMobil))
                    {
                        TempData["message"] = "  شماره تماس  شما جهت ارسال شناسه امنیتی ثبت نشده است  .     ";

                        return RedirectToAction("search", "DWHEmpPayWagNews");
                    }
                    else if (Suser != null)
                    {
                        if (db.RandomNumbers.Where(r => r.NationCode == Suser.NationCode && r.acnt == Suser.Acnt).Count() > 0)
                        {
                            var InstanceRand = db.RandomNumbers.Where(r => r.NationCode == Suser.NationCode && r.acnt == Suser.Acnt).FirstOrDefault();

                            InstanceRand.EditTime = Convert.ToString(DateTime.Now.ToShortTimeString());
                            InstanceRand.EditDate = utility.PertionDate.Today();
                            InstanceRand.NationCode = Suser.NationCode;
                            InstanceRand.Father = Suser.Fthr;
                            InstanceRand.Fname = Suser.Name;
                            InstanceRand.Mobile = Suser.TelMobil;
                            InstanceRand.acnt = Suser.Acnt;
                            InstanceRand.Lname = Suser.Fmly;
                            InstanceRand.SequrityCode = Code.ToString();
                            db.Entry(InstanceRand).State = EntityState.Modified;
                            db.SaveChanges();
                            utility.SmSSender.SendSmSCode(TelMobil, Suser.Name +" "+ Suser.Fmly, Code.ToString());
                            TempData["message"] = "همکار گرامی پیامک حاوی کد شناسه امنیتی برای شما ارسال خواهد شد.......";
                            return RedirectToAction("search", "EmpPayWagQazvins");
                        }
                        else
                        {
                            InsertCode.SequrityCode = Code.ToString();
                            InsertCode.EditDate = utility.PertionDate.Today();
                            InsertCode.EditTime = Convert.ToString(DateTime.Now.ToShortTimeString());
                            InsertCode.NationCode = Suser.NationCode;
                            InsertCode.Father = Suser.Fthr;
                            InsertCode.Fname = Suser.Name;
                            InsertCode.Mobile = Suser.TelMobil;
                            InsertCode.acnt = Suser.Acnt;
                            InsertCode.Lname = Suser.Fmly;

                            InsertCode.Time = Convert.ToString(DateTime.Now.ToShortTimeString());
                            InsertCode.Date = utility.PertionDate.Today();
                            db.RandomNumbers.Add(InsertCode);
                            db.SaveChanges();
                            utility.SmSSender.SendSmSCode(TelMobil, Suser.Name + " " + Suser.Fmly, Code.ToString());

SalaryV2/Views/RandomNum/Create.cshtml
@model SalaryV2.Models.RandomNumber

<div class="modal-header Mheader">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <p class="modal-title Mheader" id="myModalLabelEP">آیا از ارسال شناسه امنیتی به شماره موبایل ثبت شده اطمینان دارید؟  </p>
</div>
<style>
    .Mheader {
        color: white;
        text-align: center;
        font-family: Tahoma;
        font-size: large;
        background-color: #ff6a00;
    }

    .ch {
        color: darkred;
    }
</style>
@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.RandId)
    <div class="modal-body">
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)
        <div class="form-horizontal">
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="row">
                        <div class="box box-warning">
                            <div class="box-header with-border">
                                <h3 class="box-title">    </h3>
                                <div class="box-tools pull-right">
                                    <button type="button" class="btn btn-box-tool" data-widget="collapse">
                                        <i class="fa fa-minus"></i>
                                    </button>
                                    <button type="button" class="btn btn-box-tool" data-widget="remove">
                                        <i class="fa fa-times"></i>
                                    </button>
                                </div>
                            </div>
                            <div class="box-body no-padding">
                                <div class="panel-body">
                                    
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
    <div class="modal-footer">
        <span id="progress" class="text-center" style="display: none;">
            <img src="~/Content/Images/Wait.gif" alt="wiat" />
            Wait..
        </span>

        <button class="btn" type="button" data-dismiss="modal">Cancel</button>
        <input class="btn btn-danger waves-effect waves-light" type="submit" value="ثبت تغییرات" />
    </div>
}
<script>

    $("form").removeData("validator");
    $("form").removeData("unobtrusiveValidation");
    $.validator.unobtrusive.parse("form");
    $(document).ready(function () {
        $('input').iCheck({
            checkboxClass: 'icheckbox_flat-red',
            //checkboxClass: 'icheckbox_square',
            radioClass: 'iradio_square',
            increaseArea: '20%' // optional
        });
    });

</script>

SalaryV2/Views/RandomNum/GenerateCode.cshtml
@model SalaryV2.Models.GetCode
@{
    ViewBag.Title = "..: فرم ایجاد شناسه امنیتی  :..";
}
<style>
    .panel-heading{
        text-align:center;
    }
</style>
<br />
<br />
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="  form-horizontal">
     
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
              <div class="panel panel-info">
                  <div class="panel-heading">
                      ایجاد شناسه امنیتی
                  </div>
                  <div class="panel-body">
                      @if (TempData["message"] != null)
                      {
                          <div class="alert alert-success" style="color:#a30e0e;font-family:Tahoma;font-size:medium;text-align:center">
                              @TempData["message"]
                          </div>
                      }
                          <div>
                              @Html.DropDownList("Contid", null, "---انتخاب نوع قرار داد---", new { @class = "form-control input-lg" })
                          </div>
                      <div>
                          <span class="fa fa-star faa-wrench animated " style="color:#a70808"></span>
                          کد ملی
                          <div style="">
                              <div class="input-group" style="margin-bottom: 10px">
                                  <span class="input-group-addon">
                                      <i class="fa fa-id-card fa-2x">
                                      </i>
                                  </span>
                                  @Html.TextBoxFor(model => model.e1, new { @class = "form-control input-lg", placeholder = "   کد ملی", autocomplete = "off" })
                              </div>
                              <b>
                                  @Html.ValidationMessageFor(model => model.e1, "", new { @class = "text-danger" })
                              </b>
                          </div>
                      </div>
                      <div>
                          <span class="fa fa-star faa-wrench animated " style="color:#a70808"></span>

                          شماره حساب
                          <div style="">
                              <div class="input-group" style="margin-bottom: 10px">
                                  <span class="input-group-addon">
                                      <i class="fa fa-id-card fa-2x">

                                      </i>
                                  </span>
                                  @Html.TextBoxFor(model => model.b2, new { @class = "form-control input-lg", placeholder = "   شماره حساب", autocomplete = "off" })
                              </div>
                              <b>
                                  @Html.ValidationMessageFor(model => model.b2, "", new { @class = "text-danger" })
                              </b>
                          </div>
                      </div>

                  </div>
                  <div class="row">
                      <div class="form-group">
                          <div class="col-lg-offset-4 col-md-8">
                              <button class="btn  btn-success  fa-x" data-last="Finish ">
                                  ایجاد  شناسه  
                                  <i class="fa fa-floppy-o"></i>
                              </button>
                              <a href="@Url.Action("search", "EmpPayWagQazvins")" class="btn btn-default fa-x">
                                  بازگشت
                                  <i class="fa fa-arrow-left"></i>

                              </a>
                          </div>
                      </div>
                  </div>
              </div>
            </div>
        </div>
    </div>
}

<footer>
    <hr />

    <div style="text-align:center">
        <img src="~/Content/Image/salaryfooter.png" style="" />
    </div>
</footer>

SalaryV2/Views/RandomNum/Index.cshtml
@model IEnumerable<SalaryV2.Models.RandomNumber>

@{
    ViewBag.Title = "..::..";
    var Str = @TempData["message"];
}
<div class="col-md-12">
    @if (TempData["message"] != null)
    {
        <div class="alert alert-danger" style="color:#a30e0e;font-family:Tahoma;font-size:medium;text-align:center">
            @TempData["message"]
        </div>
    }
</div>
<div class="panel panel-default">
    <div class="panel-heading">
        لیست کارمندان  
    </div>
    <div class="panel panel-body">
        <div class="table-responsive">
            <table id="example" class="table table-bordered table-striped table-responsive ">
                <thead>

                    <tr>
                        <th># </th>
                        <th style="width:25%">نام و نام خانوادگی </th>
                        <th> نوع قرارداد  </th>
                        <th> نام پدر </th>
                        <th> شناسه امنیتی </th>
                        <th>شماره موبایل  </th>
                        <th>کد ملی    </th>
                        <th>   شماره حساب  </th>
                        <th> تاریخ دریافت آخرین کد </th>
                        <th> زمان دریافت آخرین کد </th>
                        <th>ارسال پیام کد امنیتی</th>
                        <th>
                            <a href="@Url.Action("CreateSendCode", "RandomNum")" class="data-modal mstyle " role="button"><i class="fa fa-envelope-o  fa-3x " style="color:#ff0000"></i></a>
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                    <tr>
                        <td></td>
                        <td style="width:25%">
                            @Html.DisplayFor(modelItem => item.Fname) &nbsp; @Html.DisplayFor(modelItem => item.Lname)
                        </td>
                        <td>
                            @if (item.Type == "1")
                            {
                                <p>شرکتی</p>
                            }
                            else
                            {
                                <p>غیر شرکتی</p>
                            }
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Father)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.SequrityCode)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Mobile)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.NationCode)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.acnt)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.EditDate)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.EditTime)
                        </td>
                        <td></td>
                        <td>
                            <a href="@Url.Action("SendCode", "RandomNum", new { id=item.RandId})" class="data-modal mstyle " role="button"><i class="fa fa-envelope  fa-3x" style="color:#00ffff"></i></a>
                        </td>
                    </tr>
                    }
                </tbody>
                <tfoot>
                    <tr>
                        <th></th>
                        <th></th>
                        <th> </th>
                        <th></th>
                        <th></th>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
</div>
<div id='myModal' class='modal fade in'>
    <div class="modal-dialog">
        <div class="modal-content">
            <div id='myModalContent'></div>
        </div>
    </div>
</div>
<script>
    $(document).delegate('.isready', 'click', function (e) {
        e.preventDefault();
        var link = $(this);
        $.ajax({
            type: 'Post',
            url: $(this).attr('href'),
            data: null,
            success: function (data) {
                if (data == 'True') {
                    link.removeClass('glyphicon-ok-circle');
                    link.addClass('glyphicon-ok');
                    link.closest('tr').css('color', 'green');
                }
                else {
                    link.removeClass('glyphicon-ok');
                    link.addClass('glyphicon-ok-circle');
                    link.closest('tr').css('color', 'b');
                }
            },
            error: function () {
                alert('error');
            }
        });
    });
    $(document).ready(function () {
        var t = $('#example').DataTable({
            "columnDefs": [{
                'paging': true,
                'lengthChange': true,
                'searching': true,
                'ordering': true,
                'info': true,
                'autoWidth': true,
                "pageLength": 10,
                "responsive": true,
                "targets": 0,

                'stateSave': true,
            }],
            "language": {
                select: {
                    rows: "%d سطرانتخاب شده "
                },
                "sEmptyTable": "هیچ داده‌ای در جدول وجود ندارد",
                "sInfo": "نمایش _START_ تا _END_ از _TOTAL_ ردیف",
                "sInfoEmpty": "نمایش 0 تا 0 از 0 ردیف",
                "sInfoFiltered": "(فیلتر شده از _MAX_ ردیف)",
                "sInfoPostFix": "",
                "sInfoThousands": ",",
                "sLengthMenu": "نمایش _MENU_ ردیف",
                "sLoadingRecords": "در حال بارگزاری...",
                "sProcessing": "در حال پردازش...",
                "sSearch": "جستجو:",
                "sZeroRecords": "رکوردی با این مشخصات پیدا نشد",

                "oPaginate": {
                    "sFirst": "برگه‌ی نخست",
                    "sLast": "برگه‌ی آخر",
                    "sNext": "بعدی",
                    "sPrevious": "قبلی"
                },
                "oAria": {
                    "sSortAscending": ": فعال سازی نمایش به صورت صعودی",
                    "sSortDescending": ": فعال سازی نمایش به صورت نزولی"
                },

            },
            "order": [[1, 'asc']]

        });
        t.on('order.dt search.dt', function () {
            t.column(0, { search: 'applied', order: 'applied' }).nodes().each(function (cell, i) {
                cell.innerHTML = i + 1;
            });
        }).draw();
    });
</script>

SalaryV2/Views/RandomNum/_CreateSendCode.cshtml
@model SalaryV2.Models.GetCode
@{
    Layout = null;
}
<div class="modal-header mh3">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <p class="modal-title Mheader" id="myModalLabel"> آیا مایل به ارسال کد امنیتی  برای اطلاعات زیر هستید؟    </p>
</div>
<style>
    .mh3 {
        color: white;
        text-align: center;
        font-family: Tahoma;
        font-size: large;
        background-color: #8019c7;
    }
    .ch {
        color: darkred;
    }
</style>
@using (Html.BeginForm())
{
    <div class="modal-body">
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="row">
            <i class=""></i>
            <div class="col-md-12">
                @Html.LabelFor(m => Model.b2, new { @class = "control-label  validator" })
                <div style="">
                    <div class="input-group" style="margin-bottom: 10px">
                        <span class="input-group-addon">
                            <i class="fa fa-user fa-2x">
                            </i>
                        </span>
                        @Html.TextBoxFor(model => model.b2, new { @class = "form-control input-lg", placeholder = " کاربر  ", autocomplete = "off" })
                    </div>
                    <b>
                        @Html.ValidationMessageFor(model => model.b2, "", new { @class = "text-danger" })
                    </b>
                </div>
            </div>
            <div class="col-md-12">
                @Html.LabelFor(m => Model.e1, new { @class = "control-label  validator" })
                <div style="">
                    <div class="input-group" style="margin-bottom: 10px">
                        <span class="input-group-addon">
                            <i class="fa fa-user fa-2x">
                            </i>
                        </span>
                        @Html.TextBoxFor(model => model.e1, new { @class = "form-control input-lg", placeholder = " کاربر  ", autocomplete = "off" })
                    </div>
                    <b>
                        @Html.ValidationMessageFor(model => model.e1, "", new { @class = "text-danger" })
                    </b>
                </div>
            </div>
        </div>
        </div>
    <div class="modal-footer">
        <span id="progress" class="text-center" style="display: none;">
            <img src="~/Content/Images/Wait.gif" alt="wiat" />
            Wait..
        </span>

        <button class="btn" type="button" data-dismiss="modal">Cancel</button>
        <input class="btn btn-success" type="submit" value="ثبت" />
    </div>
}

SalaryV2/Views/RandomNum/_SendCode.cshtml
@model SalaryV2.Models.RandomNumber
@{
    Layout = null;
}
<div class="modal-header mh3">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <p class="modal-title Mheader" id="myModalLabel"> آیا مایل به ارسال کد امنیتی  برای اطلاعات زیر هستید؟    </p>
</div>
<style>
    .mh3 {
        color: white;
        text-align: center;
        font-family: Tahoma;
        font-size: large;
        background-color: #8019c7;
    }

    .ch {
        color: darkred;
    }
</style>
@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.RandId)
    @Html.HiddenFor(model => model.Fname)
    @Html.HiddenFor(model => model.Lname)
    @Html.HiddenFor(model => model.Mobile)
    @Html.HiddenFor(model => model.Father)
    <div class="modal-body">
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="row">
            <dl class="dl-horizontal">
                <dt>
                    نام  نام خانوادگی:
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Fname) &nbsp;&nbsp;
                    &nbsp; @Html.DisplayFor(model => model.Lname)
                </dd>
                <dt>
                    شماره حساب:
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.acnt)
                </dd>
                <dt>
                    شماره موبایل:
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Mobile)
                </dd>
            </dl>
        </div>
    </div>
    <div class="modal-footer">
        <span id="progress" class="text-center" style="display: none;">
            <img src="~/Content/Images/Wait.gif" alt="wiat" />
            Wait..
        </span>

        <button class="btn" type="button" data-dismiss="modal">Cancel</button>
        <input class="btn btn-success" type="submit" value="ثبت" />
    </div>
}